[
  {
    id: 1,
    name: "Dalgona Coffee Bubble Milk Tea",
    price: 15,
    photoName: "dagona-coffee.png",
    soldOut: false,
  },
  {
    id: 2,
    name: "Matcha Latte",
    price: 9,
    photoName: "matcha-latte.png",
    soldOut: false,
  },
  {
    id: 3,
    name: "Brown Sugar Latte",
    price: 9,
    photoName: "brown-sugar-latte.png",
    soldOut: false,
  },
  {
    id: 4,
    name: "Creme bulee Classic Milk Tea",
    price: 12,
    photoName: "creme-bulee-clasic.png",
    soldOut: false,
  },
  {
    id: 5,
    name: "Taro Slush",
    price: 10,
    photoName: "taro-slush.png",
    soldOut: false,
  },
  {
    id: 6,
    name: "Oreo Slush",
    price: 19,
    photoName: "oreo-slush.png",
    soldOut: true,
  },
  {
    id: 7,
    name: "Pineapple Slush",
    price: 20,
    photoName: "pineapple-slush.png",
    soldOut: false,
  },
  {
    id: 8,
    name: "Wintermelon Punch,m",
    price: 7,
    photoName: "wintermelon-punch.png",
    soldOut: true,
  },
  {
    id: 9,
    name: "Thai Milk Tea",
    price: 10,
    photoName: "thai-milk-tea.png",
    soldOut: false,
  },
  {
    id: 10,
    name: "Strawberry-Black0Tea",
    price: 8,
    photoName: "strawberry-tea.png",
    soldOut: true,
  },
];
